'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),ctx={console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'build/runtime.js'),'utf8'),ctx,{timeout:15000});const L=ctx.LT;
const results={tests:[],criticalPaths:[],balance:[],claims:{enginePlaythrough:true,browserPlaythrough:false,physicalGamepad:false}};
let failures=0;
function test(name,run){try{run();results.tests.push({name,passed:true});console.log('PASS '+name);}catch(error){failures++;results.tests.push({name,passed:false,error:error.message});console.error('FAIL '+name+': '+error.message);}}
const prepare=(level=1,start=0,count=4,bells=0,difficulty='normal')=>{const s=L.newState(start);for(let i=1;i<count;i++)L.recruit(s,(start+i)%8);s.bells=Array.from({length:bells},(_,i)=>i);s.settings.difficulty=difficulty;for(const h of s.roster){h.level=level;h.jp=100;h.learned=L.SKILLS.filter(sk=>sk.owner===h.id&&sk.level<=level).map(sk=>sk.id);const tier=Math.min(5,Math.floor((level-1)/3));h.weapon=`w${h.id}_${tier}`;h.armor=`a${h.id%4}_${tier}`;h.charm=`c${h.id%4}_${tier}`;}L.healParty(s);return s;};
function autoAction(b){
  const a=b.actor(),s=b.state,h=L.hero(s,a.heroId),skills=L.usableSkills(h).filter(sk=>sk.cost<=a.mp),allies=b.living('hero'),enemies=b.living('enemy');
  const dead=b.actors.find(t=>t.team==='hero'&&t.hp===0);
  if(dead){const revive=skills.find(sk=>sk.effect==='revive');if(revive)return{type:'skill',id:revive.id,target:dead.key};if(s.bag.feather>0)return{type:'item',id:'feather',target:dead.key};}
  const wounded=[...allies].sort((x,y)=>x.hp/x.maxhp-y.hp/y.maxhp)[0];
  if(wounded&&wounded.hp/wounded.maxhp<.52){const heal=skills.filter(sk=>sk.effect==='heal').sort((x,y)=>y.power*(y.all?1.5:1)-x.power*(x.all?1.5:1))[0];if(heal)return {type:'skill',id:heal.id,target:wounded.key,boost:Math.min(1,a.focus)};if(wounded.hp/wounded.maxhp<.34&&s.bag.tea>0)return{type:'item',id:'tea',target:wounded.key};}
  let best=null,bestScore=-1;
  const basic={id:'attack',cost:0,power:1,hits:1,all:false,element:L.itemById(h.weapon).element,effect:'damage'};
  for(const sk of [basic,...skills.filter(sk=>sk.effect==='damage')])for(const t of enemies){const weak=t.weak.includes(sk.element);const boost=t.stagger||weak||enemies.some(e=>e.charged)?a.focus:0;const physical=['blade','pierce','blunt'].includes(sk.element);let score=(physical?a.atk:a.mag)*sk.power*(sk.hits+boost)*(1+boost*.22)*(weak?1.16:1)*(t.stagger?1.55:1);if(sk.all)score*=enemies.length*.83;if(weak&&!t.stagger){score+=Math.min(t.guard,sk.hits+boost)*18;if(t.guard<=sk.hits+boost)score+=t.charged?130:50;}score-=sk.cost*.6;if(t.hp<score)score-=Math.max(0,score-t.hp)*.25;if(score>bestScore){bestScore=score;best={type:sk.id==='attack'?'attack':'skill',id:sk.id,target:t.key,boost};}}
  if(!best)return{type:'defend'};
  return best;
}
function simulate(s,ids,seed=123,maxActions=650){const b=new L.Battle(s,ids,seed);let actions=0;while(!['won','lost','escaped'].includes(b.phase)&&actions<maxActions){if(b.phase==='enemy')assert.equal(b.enemyTurn(),true);else {const action=autoAction(b);if(!b.act(action))throw new Error('AI produced invalid action '+JSON.stringify(action));}b.events.length=0;actions++;for(const a of b.actors){assert.ok(Number.isFinite(a.hp)&&a.hp>=0&&a.hp<=a.maxhp);assert.ok(Number.isFinite(a.mp)&&a.mp>=0);assert.ok(a.guard>=0&&a.focus>=0&&a.focus<=3);}}
  assert.ok(actions<maxActions,'Battle did not terminate: '+ids.join(','));if(b.phase==='won')b.reward();else b.sync();return{phase:b.phase,rounds:b.round,actions,hpFraction:b.living('hero').reduce((n,a)=>n+a.hp/a.maxhp,0)/s.active.length,battle:b};}
test('eight unique starting states with playable stats',()=>{for(let i=0;i<8;i++){const s=L.newState(i);assert.equal(s.start,i);assert.equal(s.active[0],i);assert.equal(s.region,i);const h=s.roster[0];assert.ok(h.hp>90&&h.mp>20);assert.equal(L.usableSkills(h).length,2);}});
test('recruitment is idempotent and formation is capped',()=>{const s=L.newState();for(let i=0;i<8;i++)L.recruit(s,i);assert.equal(s.roster.length,8);assert.equal(s.active.length,4);assert.equal(L.recruit(s,4),false);});
test('equipment restrictions, inventory conservation and shop transactions',()=>{const s=L.newState();s.gold=10000;const h=s.roster[0];assert.equal(L.buy(s,'w0_1'),true);assert.equal(L.equip(s,0,'w0_1'),true);assert.equal(h.weapon,'w0_1');assert.equal(s.bag.w0_0,1);const gold=s.gold;assert.equal(L.buy(s,'missing'),false);assert.equal(L.buy(s,'tea',-1),false);assert.equal(s.gold,gold);L.buy(s,'w1_1');assert.equal(L.equip(s,0,'w1_1'),false);h.secondary=1;assert.equal(L.equip(s,0,'w1_1'),true);assert.equal(L.sell(s,'w1_1'),false);assert.equal(L.sell(s,'w0_1'),true);assert.ok(s.gold<10000);for(const n of Object.values(s.bag))assert.ok(n>=0);});
test('consumables reject invalid use without consumption',()=>{const s=L.newState(),h=s.roster[0],before=s.bag.tea;assert.equal(L.useFieldItem(s,'tea',0),false);assert.equal(s.bag.tea,before);h.hp=1;assert.equal(L.useFieldItem(s,'tea',0),true);assert.ok(h.hp>1);h.hp=0;assert.equal(L.useFieldItem(s,'tea',0),false);assert.equal(L.useFieldItem(s,'feather',0),true);assert.ok(h.hp>0);h.hp=1;h.mp=0;assert.equal(L.useFieldItem(s,'tent',0),true);assert.equal(h.hp,L.stats(h).hp);assert.equal(h.mp,L.stats(h).mp);});
test('all 64 active skills execute and spend resources once',()=>{for(const sk of L.SKILLS.filter(sk=>!sk.passive)){const s=prepare(30,sk.owner,4,0);const b=new L.Battle(s,['b0'],919);const a=b.actors.find(v=>v.heroId===sk.owner&&v.team==='hero');b.current=a.key;b.phase='choose';a.focus=3;const ally=b.actors.find(v=>v.team==='hero'&&v.key!==a.key),enemy=b.living('enemy')[0];ally.hp=sk.effect==='revive'?0:1;ally.statuses.poison=3;const friendly=['heal','revive','shield','buff','cleanse'].includes(sk.effect);const target=friendly?ally:enemy;const mp=a.mp;assert.equal(b.act({type:'skill',id:sk.id,target:target.key,boost:1}),true,sk.id);assert.ok(a.mp<=mp-sk.cost+2,sk.id+' MP accounting');assert.ok(a.focus>=0);}});
test('all 32 passives have a learnable path',()=>{for(const sk of L.SKILLS.filter(sk=>sk.passive)){const h=L.createHero(sk.owner,30);h.jp=999;assert.equal(L.learn(h,sk.id),true);assert.equal(L.learn(h,sk.id),false);assert.ok(h.learned.includes(sk.id));if(sk.id.endsWith('_0'))assert.ok(L.stats(h).hp>L.stats(L.createHero(sk.owner,30)).hp);}});
test('break skips exactly one enemy action and restores guard',()=>{const b=new L.Battle(prepare(1,0,1),['b0']);const enemy=b.living('enemy')[0],a=b.living('hero')[0];enemy.guard=1;b.pressure(enemy,a,1);assert.equal(enemy.stagger,true);b.queue=[enemy.key,a.key];b.next();assert.equal(enemy.stagger,false);assert.equal(enemy.guard,enemy.maxguard);assert.equal(b.current,a.key);});
test('bosses cannot be escaped and defeat resolves',()=>{const b=new L.Battle(prepare(1,0,1),['b0']);b.current='h0';b.phase='choose';assert.equal(b.act({type:'escape'}),false);b.actors.filter(a=>a.team==='hero').forEach(a=>a.hp=0);b.next();assert.equal(b.phase,'lost');});
test('all boss entries transition phase and change weaknesses',()=>{for(const d of L.ENEMIES.filter(e=>e.boss)){const b=new L.Battle(prepare(15,0,4),[d.id]);const e=b.living('enemy')[0];const weak=e.weak.join(',');e.hp=Math.floor(e.maxhp*.49);b.current=e.key;b.phase='enemy';b.enemyTurn();assert.equal(e.phase,2);assert.notEqual(e.weak.join(','),weak);}});
test('victory rewards cannot be duplicated',()=>{const s=prepare(),b=new L.Battle(s,['e0_0']);b.living('enemy').forEach(e=>e.hp=0);b.next();const one=b.reward(),gold=s.gold,two=b.reward();assert.ok(one.gold>0);assert.equal(two.gold,0);assert.equal(s.gold,gold);assert.equal(s.kills[0],1);});
test('all 32 quests accept evidence before acceptance and complete once',()=>{const s=L.newState();for(const q of L.QUESTS){s.evidence.push(q.id);s.kills[q.region]=3;s.bells=L.unique([...s.bells,q.region]);s.flags['mail:'+((q.region+1)%8)]=true;assert.equal(L.finishQuest(s,q.id),false);s.accepted.push(q.id);assert.equal(L.questReady(s,q),true);assert.equal(L.finishQuest(s,q.id),true);const g=s.gold;assert.equal(L.finishQuest(s,q.id),false);assert.equal(s.gold,g);}assert.equal(s.completed.length,32);});
test('save roundtrip, checksum corruption, three slots and atomic write failure',()=>{const s=prepare(5,2,4,2);s.accepted=['q0'];s.flags['example']=true;const raw=L.encodeSave(s),restored=L.decodeSave(raw);assert.equal(JSON.stringify(restored),JSON.stringify(s));const bad=JSON.parse(raw);bad.payload=bad.payload.replace('220','221');assert.throws(()=>L.decodeSave(JSON.stringify(bad)));const map=new Map(),store=new L.SaveStore({getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)});for(let slot=0;slot<4;slot++){store.write(slot,s);assert.equal(store.read(slot).start,2);}const old=map.get(store.key(1));const broken=new L.SaveStore({getItem:k=>map.get(k)||null,setItem:()=>{throw new Error('quota');},removeItem:k=>map.delete(k)});assert.throws(()=>broken.write(1,s));assert.equal(map.get(store.key(1)),old);assert.throws(()=>store.read(5));assert.throws(()=>L.decodeSave('{oops'));const invalid=L.clone(s);invalid.gold=-1;assert.throws(()=>L.decodeSave(L.encodeSave(invalid)));invalid.gold=20;invalid.active=[7];assert.throws(()=>L.decodeSave(L.encodeSave(invalid)));});
test('status duration expires without permanent lock',()=>{const b=new L.Battle(prepare(12,0,4),['b0']);const a=b.living('hero')[0];a.statuses.might=2;a.statuses.poison=2;for(let i=0;i<3;i++){b.queue=[a.key];b.next();}assert.equal(a.statuses.might,undefined);assert.equal(a.statuses.poison,undefined);});
test('all eight starting heroes can finish an earned-progression campaign',()=>{
  for(let start=0;start<8;start++){
    const s=L.newState(start);for(let i=1;i<8;i++)L.recruit(s,(start+i)%8);s.active=[start,(start+1)%8,(start+2)%8,(start+3)%8];const route=[];
    for(let n=0;n<8;n++){
      const r=(start+n)%8;s.region=r;s.area='road';s.visited=L.unique([...s.visited,r]);
      for(const h of s.roster){for(const sk of L.SKILLS.filter(sk=>sk.owner===h.id&&sk.level<=h.level&&!h.learned.includes(sk.id)))L.learn(h,sk.id);const tier=Math.min(5,Math.floor(n/1.5));const gear=`w${h.id}_${tier}`;if(h.weapon!==gear){s.bag[gear]=(s.bag[gear]||0)+1;L.equip(s,h.id,gear);}}
      for(let j=0;j<3;j++){L.healParty(s);const fight=simulate(s,[`e${r}_${j}`,`e${r}_${(j+2)%6}`],start*991+n*31+j);assert.equal(fight.phase,'won',`start ${start} road ${r}`);}
      L.healParty(s);s.area='dungeon';s.puzzles[r+':dungeon']=3;const boss=simulate(s,[`b${r}`],start*131+r+2);assert.equal(boss.phase,'won',`start ${start} boss ${r}`);s.bells.push(r);route.push({region:r,level:s.roster[0].level,rounds:boss.rounds});
      for(const q of L.QUESTS.filter(q=>q.region===r)){s.accepted.push(q.id);s.evidence.push(q.id);s.flags['mail:'+((q.region+1)%8)]=true;assert.equal(L.finishQuest(s,q.id),true);}
      const save=L.decodeSave(L.encodeSave(s));assert.equal(save.bells.length,n+1);
    }
    s.region=8;s.area='final';L.healParty(s);const one=simulate(s,['final0'],start+6543);assert.equal(one.phase,'won','final form one start '+start);L.healParty(s);const two=simulate(s,['final1'],start+7712);assert.equal(two.phase,'won','final form two start '+start);s.finished=true;s.ending='test';const post=L.decodeSave(L.encodeSave(s));assert.equal(post.finished,true);assert.equal(post.bells.length,8);results.criticalPaths.push({start,route,finalRounds:[one.rounds,two.rounds],level:s.roster[0].level,completedQuests:s.completed.length,notes:'Engine simulation; road recruitment assumed accessible, full rests between encounters, chest-equivalent weapons granted per chapter. UI story/ending tested separately.'});
  }
});
test('1200 seeded representative balance simulations terminate with finite resources',()=>{
  for(const band of [{level:1,bells:0},{level:8,bells:3},{level:15,bells:7}])for(const kind of ['normal','boss']){let wins=0,rounds=0,hp=0;const seeds=200;for(let seed=0;seed<seeds;seed++){const start=seed%8,s=prepare(band.level,start,4,band.bells),r=seed%8;s.region=r;const ids=kind==='boss'?[`b${r}`]:[`e${r}_${seed%6}`,`e${r}_${(seed+2)%6}`];const result=simulate(s,ids,80001+seed*117);wins+=result.phase==='won'?1:0;rounds+=result.rounds;hp+=result.hpFraction;}const row={...band,kind,seeds,wins,winRate:wins/seeds,meanRounds:rounds/seeds,meanRemainingHp:hp/seeds};results.balance.push(row);assert.ok(row.winRate>=.7,'Normal difficulty tuned party win rate too low: '+JSON.stringify(row));}
});
results.passed=failures===0;results.failures=failures;fs.mkdirSync(path.join(root,'build/qa'),{recursive:true});fs.writeFileSync(path.join(root,'build/qa/engine-tests.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify({tests:results.tests.length,failures,criticalPaths:results.criticalPaths.length,balance:results.balance},null,2));if(failures)process.exit(1);
module.exports={L,prepare,autoAction,simulate};
